# -*- coding: utf-8 -*-
"""Q1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SC7_b9uOPZVob0OLFCNdpKdL1NgFBabj

# **Functions**

1.   Even-Odd number
"""

def even_odd_number(x):
  if x % 2 == 0:
    return(f'{x} is an even number.')
  else:
    return(f'{x} is an odd number.')

result = even_odd_number(2)
print(result)
result = even_odd_number(5)
print(result)

"""

2. Min & Max number in a List

"""

def min_max_number(List):
  List.sort()
  return f'{List[-1]} is the maximum number and {List[0]} is the minimum number.'

List = [19, 33, 100, 50, 105, 23]
result = min_max_number(List)
print(result)

"""3. Table of any number


"""

def table(x):
  for i in range(1,11):
    print (x * i)

table(9)

"""4. Factorial of a number"""

def factorial(num):
  if num < 0:
    print("Factorial of negative number  doesn't exist")
  elif num == 0 :
   return 1
  else:
    factorial = 1
    for i in range(num,1,-1):
      factorial *= i
    return factorial

factorial(1)

# Recursive logic
def fac(n):
  if n == 0 or n == 1:
    return 1
  else:
    return n*fac(n-1)

fac(6)

"""5. Sum of a List


"""

def sum(List):
  sum = 0
  for i in List:
    sum += i
  return sum

t = [100,200,300,400]
sum(t)

"""6.  Generating acsending and decending numbers sequence using loop"""

starting = int(input("Enter Starting no. "))
ending =int(input("Enter Ending no."))

def ascending_seq():
  for i in range(starting, ending, 1):
    print (i)

ascending_seq()

def descending_seq():
  for i in range(starting,ending, -1):
    print(i)

descending_seq()

"""7.  Calculating area of a circle"""

import math
def area_of_circle(radius):
  return (math.pi * pow(radius,2))

area_of_circle(5)

"""8. Convert Celsius to Fahrenheit and vice versa"""

