# -*- coding: utf-8 -*-
"""Calculator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/197u8QL-XcqqZOeN9Wc5nVNChFW7MuZzs

# **Calculator**
"""

while True:
  try:
    num1 = int(input("Enter any number:"))
    num2 = int(input("Enter second number:"))
    operation = input("Enter airthmetic operator:")
    if operation.lower() == 'sum' or operation == '+':
      print(num1 + num2)
    elif operation.lower() == 'subtract' or operation == '-':
      print(num1 - num2)
    elif operation.lower() == 'multiply' or operation == '*':
      print (num1 * num2)
    elif operation.lower() == 'divide' or operation == '/' :
      print(num1 / num2)
    elif operation.lower() == 'exit' :
      print("Exit")
      break
  except ValueError:
    print('Invalid Input')
  except Exception as ZeroDivisionError:
    print("Cannot divide by zero")